# This is a basic workflow to help you get started with Actions

name: CI
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  first_job:
    # The type of runner that the job will run on
    runs-on: self-hosted

# Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Run a one-line script
        shell: bash
        run: echo Hello, world!

